- Syntax Definitions/Sublime Settings.JSON-tmLanguage
- Syntax Definitions/Sublime Settings.tmLanguage
Not much to say - just added `(?i)` at the beginning of the regex to make it case-insensitive, as some plugins use camelCase in their key names.
> make keys case-insensitive (keyword.other.name)

- Syntax Definitions/Sublime Key Map.JSON-tmLanguage
- Syntax Definitions/Sublime Key Map.tmLanguage
`true`, `false`, and `null` (or their equivalents) are scoped in every language I've worked with as `constant.language`. I wanted to make that consistent here, because (1) syntax highlighting will now be consistent with JSON and other languages, and (2) I wanted to add `null`, which (to my knowledge) is not a Boolean value.
> Constant.numeric.boolean -> constant.language, added null

- Package/TextMate Preferences/Completions/plist tags.sublime-completions
- Package/TextMate Preferences/Completions/tmPreference keys.sublime-completions
- Package/TextMate Preferences/Plist Scope Transformation.tmPreferences
- Package/TextMate Preferences/Plist ShellVariable Transformation.tmPreferences
- Package/TextMate Preferences/Property List.sublime-syntax
- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_plist.xml
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
Now it validates a few things like:
- inside a `<dict>`, a `<key>` has to come first, followed by something else etc. followed by another `<key>` or the end of the `</dict>`
- only whitespace and comments are allowed between elements, i.e. no text except inside the leaf elements
- no attributes allowed on the elements
> separate property list syntax from tmPreferences syntax

- syntax-test_dev.py
useful for when the syntax def doesn't have any file extensions associated with it, or when the test can't use the proper file extension
> set syntax when a syntax test file is loaded

- Package/TextMate Preferences/Symbols - shellVariable.tmPreferences
- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
- better invalid scoping when things are invalid
- distinguish between known shell variables and custom ones
> improve shellVariables in tmPreferences syntax

- syntax-test_dev.py
this PR ensures that the syntax test highlighting will be consistent with what ST actually asserts against when the test assertions continue past the new line character. (In this circumstance, ST asserts against the scope at the new line character.)
EDIT: i.e. it changes it from this:
to this:
> don't extend syntax test highlighting past the newline character, plus refactor for efficiency

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
For #93. Also adds support for YAML anchors, because I'm just including functionality from the YAML syntax that does both. New tests to make sure that tags don't interfere with existing highlighting.
> Add support for YAML tags.

- Package/Sublime Text Syntax Definition/Oniguruma RegExp.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_onig-regexp
- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
ST uses the oniguruma regex engine/syntax inside `.tmPreferences` files, so it makes sense to change the syntax highlighting to use it, so that we will have correct/more accurate highlighting on things like [`\k<test+0>` where the capture group backreference can optionally target a particular relative recursion level](https://github.com/kkos/oniguruma/blob/36b89b9ba5c3dd90f7791c8d86517a4d8d82434c/doc/RE#L249)
> use oniguruma regex syntax inside tmPreferences

- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
Prior to this PR, the syntax definition wasn't scoping XML comments in shellVariables and regex patterns correctly. However, ST also has some odd behavior - specifically, ST ignores text in `tmPreferences` files if it comes after a comment or CDATA node that comes after non-whitespace. I have added `invalid.deprecated` scoping to highlight this to the developer, to save time troubleshooting when commenting bits of text out or trying to use multiple consecutive CDATA sections.
(`plistlib` still reads it correctly, so I haven't touched the "Property List" syntax definition - it's just ST's parser that behaves like this.)
> helpfully highlight text as depreciated in tmPreferences files if ST will ignore it

- Package/Default.sublime-keymap
- Package/Sublime Text Syntax Definition/Dot Commit Completion.sublime-macro
- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- plugins_/syntax_dev.py
This PR fixes #146 by resetting `is_completing_scope` if the completion popup is closed.
The following situations reset the scope completion now:
- deactivating the view
- move away from completion by cursor ("move")
- move away from completion by mouse ("drag_select")
> Fix: Cancel syntax test scope completions

- Package/Default.sublime-keymap
- plugins_/snippet_dev.py
PackageDev provides a key binding `ctrl+s` to convert snippets.
This key binding overrides the default `save` command.
Therefore a sublime-completions file can't be saved, if the cursor is within the "contents" key as its value is scoped as `source.sublime.snippet.embedded` which matches the key binding's selector.
This commit therefore
1. extends the selector of the keybinding to exclude `source.json`
2. disables the `packagedev_snippet_from_raw_snippet` in `source.json`
> Fix Save command not working in "contents" of sublime-completions

- plugins_/settings/__init__.py
- plugins_/settings/known_settings.py
For details see the commit messages, please.
Some notes/thoughts besides commits:
I also tried to remove `background-color` attributes from the CSS and keep only the modified borders. This would: 
1. avoid to possibly override color scheme colors
2. work properly for dark color schemes as ST blends the background color well
3. but doesn't look well with white backgrounds as ST blends the background too little, which still makes them barely visible on Windows.
> Improve settings tooltip visibility for white color schemes

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
- plugins_/syntax_dev.py
This PR adds support (syntax definition and completions) for the new `embed` actions for `.sublime-syntax` files added in build 3153.
Awesomely, no changes are required to the code that highlights capture groups in the syntax test files to support `escape_captures`.
> Add support for new embed actions in sublime-syntax files

- Package/Sublime Text Build System/Completions/Main Keys (in-string).sublime-completions
- Package/Sublime Text Build System/Completions/Main Keys.sublime-completions
- Package/Sublime Text Build System/Sublime Text Build System.sublime-syntax
- Package/Sublime Text Build System/syntax_test_build_system.json
while looking at https://forum.sublimetext.com/t/trying-to-create-a-debian-package-sublime-build/34430, I noticed that `keyfiles` wasn't highlighted correctly. This PR corrects that and adds the relevant completions. More info at:
- http://www.sublimetext.com/docs/3/build_systems.html#options
- https://forum.sublimetext.com/t/custom-build-system-for-rails/24609/2
- https://forum.sublimetext.com/t/build-systems/14435
- https://forum.sublimetext.com/t/dev-build-3072/14605
> Add support for "keyfiles" to sublime-build syntax highlighting

- Package/Sublime Text Menu/Sublime Text Menu.sublime-syntax
- Package/Sublime Text Menu/syntax_test_menu.json
this fixes a bug whereby the `Packages/Default/Main.sublime-menu` file would show `invalid` in places where the `!` operator is used for the platform specifier like:
```json
{ "command": "prompt_open_file", "caption": "Open File…", "mnemonic": "O", "platform": "!OSX" },
```
> correctly scope sublime-menu platform negation operator

- Package/PackageDev.sublime-settings
- plugins_/syntaxtest_dev.py
Quite often when writing syntax tests, I don't add any assertions for whitespace (unless I am adding a negation for the previous assertion to confirm the scope is no longer active), as whitespaces typically don't receive any special scopes. Therefore, when I have a file like:
```
line being tested
```
and I create a new test line and press <kbd>Tab</kbd>, I then have to press <kbd>Space</kbd><kbd>^</kbd> to get assertions for the next non-whitespace span.
```
line being tested
```
This PR allows me to set a new preference called `syntax_test.skip_whitespace` to `true`, so that I can just press <kbd>Tab</kbd> and end up with:
```
line being tested
```
Hopefully other people will also find this useful :)
> New pref to allow tabbing over whitespace during syntax test development

- Package/Sublime Text Snippet/Sublime Text Snippet.sublime-syntax
- Package/Sublime Text Snippet/syntax_test_snippet.xml
Only the encapsulated content of a <![CDATA[ content ]]> tag should be scoped as string. By scoping the beginning and the end as ordinary xml tags the readability can be improved. The content can better be distinguished from the enclosing tag.
The <![CDATA[ is parsed by the xml-parser and marks the start of text to exclude from parsing up to the ]]> tag.
This commit implements the required changes to do so and fixes a bug which causes the </content> tag after an illegal second CDATA tag to be highlighted as illegal as well.
> Snippets: Highlight CDATA as self closing tag

- plugins_/command_completions/__init__.py
- plugins_/command_completions/builtin_commands_meta_data.yaml
- plugins_/command_completions/commandinfo.py
This PR ensures that when the PackageDev `command_completions` plugin is loaded, it will check that the metadata could be loaded successfully, and warn if it couldn't. It will also log a warning if the metadata file, which is supposed to contain built-in (core) commands only, contains a command defined in the `Default` package. This will allow PackageDev developers to make changes to the metadata file, restart ST and confirm (from looking at the ST console) that the file is still parse-able and doesn't contain any mistakes. It also highlights that I shouldn't have added the indentation related commands in https://github.com/SublimeText/PackageDev/pull/190, as I forgot they exist in the `Default` package. (For some reason they weren't showing up as completions when I was trying something …
> validate built-in command  metadata

- plugins_/settings/__init__.py
The `edit` phantoms in the _*.sublime-settings_ files are set to the view's background color at the moment, which does not match the rendered background color in several situations:
- text selected
- active line background differs from view background
To fix the graphical glitches a fully transparent background is applied via CSS.
> Use transparent background for settings phantoms

- Package/Sublime Text Theme/Sublime Text Theme.sublime-syntax
- Package/Sublime Text Theme/syntax_test_newstyletheme.json
- Package/Sublime Text Theme/syntax_test_oldstyletheme.json
This is just the basics at the moment, copied from the color scheme. We will also want proper scoping of all known theme rule keys (and values) and autocompletion eventually, but this at least makes working with variables easier for now (in new the theme format).
> Initial sublime-theme syntax definition added

- Package/Sublime Text Color Scheme/Completions/Main Keys.sublime-completions
The main-keys of a sublime-color-scheme are currently being suggested within themselves.
This commit changes the selector to suggest main keys only within the top-level object where such keys are actually valid only.
> Fix: sublime-color-scheme main key completions

- plugins_/syntaxtest_dev.py
When extending assertions in syntax tests, keep extending the assertion until the asserted scope would change.
Given (curly brackets denote selection):
```js
// SYNTAX TEST "Packages/JavaScript/JavaScript.sublime-syntax"
[a, b, c, d]
//^{ meta.sequence punctuation.section.brackets.begin}
```
When you type a caret, the old result was:
```js
// SYNTAX TEST "Packages/JavaScript/JavaScript.sublime-syntax"
[a, b, c, d]
//^^{ meta.sequence}
```
And the new result is:
```js
// SYNTAX TEST "Packages/JavaScript/JavaScript.sublime-syntax"
[a, b, c, d]
//^^^^^^^^^^^^{ meta.sequence}
```
> Extend carets further in syntax test completions.

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
- plugins_/syntax_dev.py
Fixes #201
This commit fixes an issue with multi-push/multi-set contexts not being scoped as include-list, if the sequence spans multiple lines.
> Fix Context completions in multi-push statements not displayed

- plugins_/new_resource_file/templates.py
`target` does not work as the argument. `open_file` expects `file`.
> "target" changed to "file"

- Package/Sublime Text Syntax Definition/References - Context.tmPreferences
- Package/Sublime Text Syntax Definition/References - Variable.tmPreferences
This commit prepares PackageDev to correctly show all references of `contexts` and `variables` in the Goto Definition Popup in case https://github.com/SublimeTextIssues/Core/issues/2546 gets fixed some day.
This allows navigation between the definition of contexts/variables and all usages.
> Add contexts and variable to syntax reference list

- plugins_/syntax_dev.py
This commit adds the `first_line_match` keyword to the list of base_keys to complete in root level of sublime-syntax files.
> Add `first_line_match` to auto-completions in sublime-syntax

- Package/Default.sublime-keymap
- Package/Sublime Text Syntax Definition/Add Syntax Rule.sublime-macro
- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-settings
This commit adds some key bindings to:
1. auto-insert a newline, when typing a `:` after a context key. Context keys are recognized by being indented by at most two characters and not starting with `- `.
2. auto-insert a space after the first typed `:` in a line. This rule applies to situations when rules are inserted manually (not by auto-completion) or correcting them.
3. auto-insert space and trigger auto-completion, when typing the first `-` in a line, which indicates a new rule to be added. Up to this commit typing `-` directly triggers auto-completion as `-` was removed from word-separators. Committing the completion results in malformed yaml (e.g. -match: '').
Furthermore this commit adds a syntax-specific setting to ensure to trim trailing spaces, if the sublime-syntax file is …
> Add some input helpers for sublime-syntax files

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
This reverts commit 832c2cfa16f042c8bc4fcaaa58ed6857bf3091d8.
This commit probposes to revert 832c2c as it breaks command completions in the first line after a push/set statement.
The first line after a push/set can either be
- the start of a list of included contexts
- or it can contain normal commands like `- match`.
Hence auto-completion must suggest the merged list of available contexts and the normal command completions if the cursor is in the first line.
This does not work in v3.2.2 due to the mentioned commit.
We only see context completions now.
> Revert "Fix context completions in multi-line push rules"

- Package/Default.sublime-keymap
After some further days of working with, I found some edge cases with
my recently proposed key bindings.
1. Adding a new-line after a `:` is not a good idea in the `variables`
context. Therefore I'd suggest to limit this function to `contexts`.
The only left key it might be useful with is the `file_extensions`
key. Not sure if it makes sense to add it as well.
2. The other way round, adding a space after the first `:` would make
sense in the `variables` context, if it does not yet exist.
> Refine input helpers for sublime-syntax

- Package/Sublime Text Theme/Completions/Elements (in-string).sublime-completions
According to a recent forum post the following theme elements are now supported to style the new vcs status bar indicators.
> Theme: Add status bar VCS indicator elements

- Package/Sublime Text Color Scheme/References - Variable.tmPreferences
- Package/Sublime Text Theme/References - Variable.tmPreferences
- Package/Sublime Text Theme/Symbols - Class Selectors.tmPreferences
- Package/Sublime Text Theme/Symbols - Variable.tmPreferences
This commit enables Goto Definition/Goto Reference for variables in
- sublime-color-schemes
- sublime-themes
> Theme/Scheme: Add symbol/reference lists for variables

- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-settings
- Package/Sublime Text Theme/Sublime Text Theme.sublime-settings
The hyphen is removed from the list of word separators to fix goto definition/reference for variables, whose names contain them.
> Theme/Scheme: Variables can contain hyphens

- Package/Sublime Text Theme/Sublime Text Theme.sublime-syntax
- Package/Sublime Text Theme/syntax_test_newstyletheme.json
ST 3179+ supports CSS colors in `tint_modifier` and `accent_tint_modifier` keys.
> Theme: Fix CSS color support for tint_modifier

- Package/Sublime Text Theme/Completions/Rule Keys.sublime-completions
This commit fixes an issue with completions of "Rule Keys" with floating point values.
Before this commit the completions suggest sequence values.
Before:
"font.size": [11.0]
After:
"font.size": 11.0
> Theme: Fix float-value rule completions

- Package/Sublime Text Theme/Completions/Rule Keys.sublime-completions
This commit enables rule completions in "parent" mappings:
"parents": [
{"class": "dialog", "attributes": ["file_light"]}
^^^^^ ^ here
],
> Theme: Enable rule completions in the parent mapping

- plugins_/color_scheme_dev.py
This commit adds all the `--...ish` like colors to the variable completions. The completions are implemented in the color_scheme_dev.py to create consistent results with all the locally defined variables and to work around an issue of the sublime-completions file format, which prevents triggers beginning with none-word characters.
> Theme/Scheme: Add builtin color completions

- Package/Sublime Text Theme/Completions/Attributes (in-string).sublime-completions
- Package/Sublime Text Theme/Completions/Attributes.sublime-completions
- Package/Sublime Text Theme/Sublime Text Theme.sublime-syntax
This commit
1. adds `missing` and `deleted` vcs status attribute values
2. sorts all values according to the theming guideline
see: https://www.sublimetext.com/docs/3/dev/themes.html -> file_system_entry -> attributes
> Theme: Add more VCS status attributes

- Package/Sublime Text Theme/Sublime Text Theme.sublime-syntax
This commit accociates the `hidden-theme` extension with the `Sublime Text Theme` syntax. There is no such hidden theme out in the wild so far, but the naming follows the `Sublime Text Color Scheme` syntax which uses `hidden-color-scheme`
> Theme: Add 'hidden-theme' extension

- plugins_/lib/scope_data/data.py
This commit updates completions for sublime-syntax development according to the new scope naming guidelines, which are not yet covered by another PR.
see: https://www.sublimetext.com/docs/3/scope_naming.html#constant
Note: The keywords `extends` and `throws` are no longer part of the scope naming guideline. They are therefore removed from the completions.
> Syntax: Update a couple of completions

- Package/Sublime Text Build System/Sublime Text Build System.sublime-syntax
- Package/Sublime Text Project/Completions/Build System Keys (in-string).sublime-completions
- Package/Sublime Text Project/Completions/Build System Keys.sublime-completions
- Package/Sublime Text Project/Sublime Text Project.sublime-syntax
- Package/Sublime Text Project/syntax_test_project.json
The `build_systems` dictionary in a sublime-project file does not
contain a build system variant, but a list of full featured build
systems.
This means `selector` is a valid key. Additionally the `name` key is
used to identify the build system.
Note:
The completions selectors might need to be tweaked a bit as some
glitches were encountered. main keys are suggested within the `cmd`
value part for instance. Looks like another issue.
> Project: Fix Build Systems mapping

- Package/Sublime Text Keymap/Sublime Text Keymap.sublime-syntax
Per the [scope naming conventions for `string.`](https://www.sublimetext.com/docs/3/scope_naming.html#string), open quotes should use the scope `punctuation.definition.string.begin` instead of `punctuation.definition.string.start`.
> Update scope used in Keymap syntax to follow conventions

- Package/Scope Selector.sublime-syntax
- Package/Sublime Text Snippet/Sublime Text Snippet.sublime-syntax
- Package/Sublime Text Snippet/syntax_test_snippet.xml
Fixes #255
Remove capture groups to make `&amp;` being matched correctly within the Scope Selector.sublime-syntax
> [Snippets] Fix selector after &amp; operator

- plugins_/command_completions/builtin_commands_meta_data.yaml
This commit adds completions for builtin project and workspace related commands.
> Add completions for builtin commands

- plugins_/settings/known_settings.py
Had a look at  8b904c6 and found some possible edge cases to fix.
While looking into it, I found the `(default)` marker not to be added to `color_scheme` and `theme` completions. Fixed it by extending the `format_completion_item()`. 
Finally found the `color_scheme` completions missing the `sublime-color-scheme` files and fixed it.
_Note:_
The extended `format_completion_item()` could be used in `_completions_from_comment()` and `_completions_from_default()` to add the `(default)` mark, which would result in `_marked_default_completions()` not being needed anymore. Left that for now as I am not sure whether it was the better alternative.
The main reason for extending `format_completion_item()` was to avoid breaking the description part of the completion label by calling …
> Settings: Improve completions of known values

- plugins_/settings/known_settings.py
Btw. nice changes done in the recent commits. To continue completing each others ideas, this PR proposes some fixes for regressions introduced by 30983c799d9b048bb1ab5795fe117c70c1969f8e which cause:
1. duplicated completions (e.g.: "caret_style") and
2. missing `(default)` marks for list values (e.g.: "indent_guide_options").
The method `_completions_from_comment()` needs to do default marking in order to prevent `_completions_from_default()` to add the same value.
The `format_completion_item()` function needs to handle `list` type default values when setting `is_default`.
Force `_completions_from_default()` to mark values added from the `default` list by passing `is_default=True` to the `format_completion_item()`. It's just an optimization to avoid the `value in default` check.
> Settings: Fix duplicated value completions

- plugins_/command_completions/builtin_commands_meta_data.yaml
> Update list of builtin commands

- plugins_/command_completions/builtin_commands_meta_data.yaml
Closes #268
This PR contains two commits:
The first one adds globally used buitin commands, which are not yet part of the commands_meta_data.
The second proposes to add commands which are used in the find/replace panels only. Not sure whether they should be added or not.
> Add missing builtin commands

- plugins_/lib/scope_data/data.py
This adds `punctuation.definition.numeric.base` to the scope data, so that it will be suggested in the auto completions when writing syntax definitions. (This was recently standardized, see i.e. https://github.com/sublimehq/Packages/pull/2175)
> add scope completion for punctuation.definition.numeric.base

- plugins_/lib/scope_data/data.py
This reverts commit d59b57e6e2bd6f7b1c8214a355dccf8377b38940.
The sublimehq team has decided to remove this from the core syntaxes before a ST4 stable release.
The only reason for that not to have happened yet is the pending discussion at https://github.com/sublimehq/Packages/pull/2229, which should provide a the answer about how to go on either by adding the proposed meta.scopes or just remove the punctuation scope.
Therefore we should not encourage anyone to use those scopes in the meanwhile by adding them to the completions here.
> Revert "add scope completion for punctuation.definition.numeric.base"

- plugins_/syntaxtest_dev.py
ST supports whitespace in the middle of the syntax test token, but PackageDev wasn't offering any syntax test completions. This fixes that oversight to bring PackageDev back in line with ST behavior.
> fix bug preventing whitespace in the syntax test token

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
It is a valid syntax to put the included context name to the line after a `push:` or `set:` statement.
> Syntax: Fix highlighting of included contexts

- plugins_/syntaxtest_dev.py
support for this was added in Sublime Text build 4069. Without this change, syntax test files that also test indentation were not being detected by PackageDev's syntax test helper plugin. With this change, we don't do anything with the information that indentation is also being tested (except store it in the `SyntaxTestHeader`), but it allows the plugin to operate normally.
> correctly handle indentation keywords in the syntax test header

- plugins/lib/scope_data/data.py
Is used by a fair enough number of default syntaxes.
> Syntax: Add scope for comparison operator

- plugins/syntaxtest_dev.py
This commit fixes an issue which causes wrong selectors to be suggested, when typing following test cases:
// <-|
Note: `|` denotes the caret.
The reason is the caret's column being used to extract scope names instead of the one from the calculated assertion range. The assertion's column is the one of the first character of the comment punctuation.
before this commit:
</style>
with this commit:
</style>
> Syntax: Fix testcase scope completion

- Package/Default.sublime-keymap
- Package/Sublime Text Syntax Definition/Oniguruma RegExp Indentation Rules.tmPreferences
- Package/Sublime Text Syntax Definition/Trim Add Newline.sublime-macro
This PR proposes to ...
1. align the caret with the `match` keyword when pressing enter.
The result is:
```
- match: pattern
|
```
Before it was:
```
- match: pattern
|
```
Note: This might also be achieved by indentation rules, but I had no luck with them so far.
2. trim spaces after `push: `, `set: `, ... if enter is pressed and adds an indented line afterwards.
Note: The macro works only for this special purpose as `delete_word` also removes the colon.
3. removes automatic insertion of linefeed when typing colon after context names as it often ends in empty lines after editing context names.
> Syntax: Update input helper

- Package/Main.sublime-menu
- Package/PackageDev.sublime-commands
Seems like every other occurrence is either a capitalized proper name,
or a fully lowercase identifier (e.g. in a scope name).
---
This is a legit one-letter-fix PR. I'm so sorry everyone.
PS Don't forget to tag [@shitoberfest](https://twitter.com/shitoberfest/) when posting this.
> TextMate: use the correct brand capitalization

- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-syntax
It is already included in `CSS.sublime-syntax#numeric-values`.
> Color Scheme: Remove CSS.sublime-syntax#percentage-value

- Package/Sublime Text Keymap/Completions/Context Key Values.sublime-completions
- Package/Sublime Text Keymap/Sublime Text Keymap.sublime-syntax
This PR adds context keys that have been added in various builds of ST4 starting from 4050. The following table summarizes them
| Key                           | Operand | Operators | Match All | Description                                                                | Added in |
|-------------------------------|---------|-----------|-----------|----------------------------------------------------------------------------|----------|
| `"overlay_has_focus"`         | boolean | equality  | no        | Whether the overlay currently open, has focus.                             | 4082     |
| `"overlay_name"`              | string  | equality  | no        | The name of the overlay. Valid values are `"goto"` & `"command_palette"`   | 4082     |
| `"group_has_multiselect"`     | boolean | …
> [ST4] Add new context keys.

- plugins/lib/scope_data/__init__.py
- plugins/syntax_dev.py
- plugins/syntax_dev/__init__.py
- plugins/syntax_dev/completions.py
- plugins/syntax_dev/highlighter.py
This PR...
1. is meant for ST4 only at its final stage. (Until https://github.com/SublimeText/PackageDev/commit/122beaa680bc5dbfd831563a4c4166dffa651699 both ST3 and 4 are supported).
2. creates a `syntax_dev` package to split highlighting and completions into separate modules.
3. completions from base syntaxes are still missing (`extends` needs to be added).
It is a set of ideas of how completions may work in future releases. It already works pretty good - may need some structural improvements though.
> Syntax: Add kind info for ST4

- Package/Sublime Text Color Scheme/Completions/Globals Keys.sublime-completions
- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-syntax
This PR
1. Adds appropriate completions for various `block_caret_` global settings introduced in 4086.
2. Adds these in the syntax file for appropriate highlighting.
Here is a brief summary of them.
1. `block_caret_corner_style`: Controls the corner style of block carets. Valid values are `cut`, `round` & `square`.
2. `block_caret_border`:  Controls the color of the block caret's border.
3. `block_caret_underline`: Controls the color of the block caret **inside a selection**. The color of the block caret inside a selection will fallback to the color of the `caret` global if `block_caret_underline` is not defined.
4. `block_caret_corner_radius`: Controls the corner radius of block caret. This value lies in the range `[0, 10]`
> [ST4] Add support for various `block_caret_` global settings in color schemes.

- plugins/lib/scope_data/__init__.py
Not only `sorted` is useless because of ST sorting completion suggestions by relevance it also breaks the function itself.
The scope names don't have kind info or annotation applied.
Removing `sorted` fixes that.
> Scopes: Fix completions

- Package/Sublime Text Build System/Completions/Exec Keys (in-string).sublime-completions
- Package/Sublime Text Build System/Completions/Exec Keys.sublime-completions
- Package/Sublime Text Build System/Sublime Text Build System.sublime-syntax
This PR
1. Adds completions for `kill_previous` (introduced in 4092 to kill previously running builds) & `update_annotations_only` (introduced in 4050) to the build system completions file. These are also added to the syntax file for appropriate highlighting.
2. It removes any phantom related `exec` args from the completions & syntax file since phantoms are no longer used to show build errors in the buffer from 4050 onwards.
> [ST4] Some changes to build system completions & updating it's syntax.

- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-syntax
- Package/Sublime Text Color Scheme/syntax_test_colorscheme.json
- Package/Sublime Text Theme/syntax_test_newstyletheme.json
This commit adds `color-var-function` context to `color-adjuster-string-pop` in order to highlight var() function correctly.
While adding test cases another inconsistency with regards to group punctuation was revealed and fixed.
> Themes: Add var() function support to color-adjuster context

- Package/Sublime Text Color Scheme/Completions/Globals Keys (in-string).sublime-completions
- Package/Sublime Text Color Scheme/Completions/Globals Keys.sublime-completions
- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-syntax
This PR adds the following missing global keys to the completions and syntax file for appropriate highlighting.
1. `gutter_foreground_highlight`.
2. `scroll_highlight`
3. `scroll_selected_highlight` 
These are documented in https://www.sublimetext.com/docs/color_schemes.html#global_settings:ver-dev
> [ST4] Add a few missing color scheme global keys. 

- Package/Sublime Text Color Scheme/Completions/Globals Keys (in-string).sublime-completions
This PR syncs the `Globals Keys (in-string).sublime-completions` to that of `Globals Keys.sublime-completions`.
Some of the missing keys were:
1. `block_caret_corner_style`
2. `block_caret_border`
3. `block_caret_underline`
4. `block_caret_corner_radius`
These were added in ac80cf7d9d681677b023d21d146143ef68f2c0c8 but looks like I forgot to add them to string completions.
> [ST4] Sync the in string completions to that of global keys completions for color scheme.

- Package/Sublime Text Commands/Completions/Platform Names.sublime-completions
- Package/Sublime Text Commands/Sublime Text Commands.sublime-syntax
- Package/Sublime Text Commands/syntax_test_commands.json
- Package/Sublime Text Menu/Sublime Text Menu.sublime-syntax
This PR
1. Adds support for the `platform` key in `.sublime-commands` introduced in Build 4094 to support platform specific entries in the command palette.
2. Added completions for `platform` names.
This is essentially just a copy of what exists for the `.sublime-menu` file (Both the contexts and the completions). Maybe we need a way to reuse them ?
> Commands: Add support for the platform key

- Package/Sublime Text Commands/Completions/Main Keys (in-string).sublime-completions
- Package/Sublime Text Commands/Completions/Main Keys.sublime-completions
- plugins/file_conversion.py
- plugins/new_resource_file/__init__.py
- plugins/snippet_dev.py
- plugins/syntax_dev/completions.py
- plugins/syntax_dev_legacy.py
This PR
1. Makes use of `Window.status_message` instead of `sublime.status_message`.
2. Uses `View.assign_syntax` instead of `View.set_syntax_file` (which uses `assign_syntax` internally).
3. I did not find any instances of usage of `Window.get_output_panel` apart from that in comments.
PS: I have also slipped in a commit to add completions for the `platform` key which was added in 3f858fd7997a8dd3ff85d5ac63584214983542ea (which I unfortunately forgot to add, but did not seem well worth a seperate PR).
Resolves #336
> Remove the use of deprecated API endpoints.

- Package/Sublime Text Settings/Preferences.sublime-settings-hints
Related: https://github.com/SublimeText/PackageDev/pull/343
> Add a few more undocumented settings.

- plugins/color_scheme_dev.py
- plugins/theme_dev.py
This PR adds the ability to make editing color schemes/themes OS aware, when the corresponding settings are set to `auto`. The quick panel item that is active is selected and has an annotation of `Active` based on the OS appearance mode. 
Resolves #329
> [ST4] Make editing scheme/theme, OS aware when the corresponding is set to auto.

- Package/PackageDev.sublime-settings
- plugins/syntaxtest_dev.py
The implementation isn't necessarily final, but feedback would be appreciated.
First, a motivating example. The pipe denotes the cursor, and `syntax_test.suggest_scope_suffix` is false.
Before:
```js
if ( true ) { }
//  ^^^^^^^^^^^^^^^ meta.conditional
//  ^^ keyword.control.conditional.if
//     |
```
Ordinary result of typing `^`:
```js
if ( true ) { }
//  ^^^^^^^^^^^^^^^ meta.conditional
//  ^^ keyword.control.conditional.if
//     ^ meta.conditional meta.group punctuation.section.group.begin|
```
With `"syntax_test.suggest_trimmed_prefix": true`:
```js
if ( true ) { }
//  ^^^^^^^^^^^^^^^ meta.conditional
//  ^^ keyword.control.conditional.if
//     ^ meta.group punctuation.section.group.begin|
```
---
The implementation is a first pass, but it's probably mostly correct. Notes:
- The …
> Trim redundant prefixes of syntax test suggestions.

- Package/Sublime Text Theme/Completions/Rule Keys.sublime-completions
`layer#.draw_center` defaults to `true`, it makes more sense to override it with `false`.
> Changed value of `layer.draw_center` to `false`

- LICENSE
- Package/Sublime Text Color Scheme/Sublime Text Color Scheme.sublime-settings
I removed `#` from the color scheme `word_separators` so hex colors can be completely selected on double-click. I also updated the year in the `LICENSE` to 2021. This will need to be changed again in 2 months. Maybe somebody can write an action for that...
> Update color scheme word_separators, change LICENSE year

- plugins/settings/known_settings.py
The root cause was that text manipulation was reordered in a wrong way:
JSON-encoded string was converted to snippet-field-content-encoded
string first, but then it was treated as a simply JSON-encoded string
again. Namely, stripping curly brackets away _after_ encoding them
as \\} broke cursor things in a weird ways.
Used pretty printing just because it looks better. But it required extra
whitespace stripping: both outside and inside stripped
brackets/braces.
Also changed variable name from `encoded` to `content` in fmt, so they
can never be accidentally reordered again.
Fixes #347
> Settings: Fix completion values

- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/Symbols - Section.tmPreferences
It's not an official feature of a sublime-syntax file, but as I started to split syntaxes into sections for better readability I'd find it a good idea to also use them for navigation.
Syntaxes which make use of sections are:
- HTML (ASP) (master)
- Bash (master)
- CSS (master)
- Erlang (master)
- Haskell (see: https://github.com/sublimehq/Packages/pull/2679)
- HTML (master)
- Java (see: https://github.com/sublimehq/Packages/pull/2654)
- Markdown (some in master)
- Matlab (see: https://github.com/sublimehq/Packages/pull/2650)
- Perl (master)
- Ruby (some in master)
- XML (master)
Inspired by the contexts recently added to R.
see: https://github.com/sublimehq/Packages/commit/d43b3b7f92d306cfad6cac8e0c0574ef5f4afff5
> Syntax: Add highlighting for section comments

- plugins/syntaxtest_dev.py
This fixes the bug whereby opening a `syntax_test_` file from `OverrideAudit: Open Resource` etc. would open without the syntax being assigned automatically from the syntax test header line.
The `on_load` event listener is fired before the file was read from the `.sublime-package` file, meaning the view is still empty, causing it to miss the syntax test header. So, this commit changes the behavior so that, if it sees that the file being loaded resides within the package catalog, and is empty, then it will re-try after a short delay.
> Fix syntax definition automatic assignment for syntax test files

- main.py
This commit enables reloading all sub modules by just saving `main.py`.
There's no real need to restrict plugin reloading to Package Control
updates. Reloading should work properly without Package Control as well.
That strategy is already used successfully by several packages, such as
A File Icon, GitGutter, MarkdownEditing and maybe more.
> Don't restrict plugin reloading to Package Control Updates

- .github/workflows/syntax.yml
- Package/Property List/Completions/Tags.sublime-completions
- Package/Property List/Property List.sublime-syntax
- Package/Property List/Snippets/plist (in-tag).sublime-snippet
- Package/Property List/Snippets/plist.sublime-snippet
- Package/Property List/syntax_test_plist.xml
- Package/Scope Selector (XML).sublime-syntax
- Package/Scope Selector.sublime-syntax
- Package/TextMate Preferences/Completions/Main Keys (in-key).sublime-completions
- Package/TextMate Preferences/Completions/Main Keys.sublime-completions
- Package/TextMate Preferences/Completions/Settings Keys (in-key).sublime-completions
- Package/TextMate Preferences/Completions/foldScopes Keys (in-key).sublime-completions
- Package/TextMate Preferences/Completions/foldScopes Keys.sublime-completions
- Package/TextMate Preferences/Completions/shellVariable Keys (in-key).sublime-completions
- Package/TextMate Preferences/Completions/shellVariable Keys.sublime-completions
- Package/TextMate Preferences/Completions/shellVariable Name.sublime-completions
- Package/TextMate Preferences/Snippets/foldScopes Entry.sublime-snippet
- Package/TextMate Preferences/Snippets/plist (in-tag).sublime-snippet
- Package/TextMate Preferences/Snippets/plist.sublime-snippet
- Package/TextMate Preferences/Snippets/shellVariables Entry.sublime-snippet
- Package/TextMate Preferences/Symbols - scope.tmPreferences
- Package/TextMate Preferences/Symbols - setting.tmPreferences
- Package/TextMate Preferences/Symbols - shellVariable.tmPreferences
- Package/TextMate Preferences/TextMate Preferences.sublime-settings
- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
- messages.json
- messages/3.4.0.txt
Fixes #377
This PR ...
1. completely refactors/rewrites _Property List_ and _TextMate Preferences_ syntax
- switch to sublime-syntax v2
- inherit TextMate Preferences from Property List
- introduce a common scheme of context structure for all kinds of tags for consistent behavior
- adds a bailout to not escalate illegal highlighting beyound array/dict boundaries.
3. adjusts completions/snippet selectors
4. fixes broken and cleans up obsolete completion/snippet selectors
5. adds some completions/snippets
6. fixes Goto Symbol for various symbols
Note: Majority of scopes is kept unchanged or tweaked only a little bit as many packages/color schemes seem to rely on them.
> TextMate Preferences: Refactor Syntax

- plugins/command_completions/builtin_commands_meta_data.yaml
This PR extends arguments of built-in `show_panel` command by...
1. `console` panel name
2. `toggle` and `toggle_when_not_focused` arguments
> Add missing `show_panel` arguments

- Package/TextMate Preferences/Completions/shellVariable Name.sublime-completions
- Package/TextMate Preferences/TextMate Preferences.sublime-syntax
- Package/TextMate Preferences/syntax_test_tmPreferences.xml
Proposed in a [GitHub issue][1] and introduced in [Sublime Text 4153][2].
[1]: https://github.com/sublimehq/sublime_text/issues/6001
[2]: https://www.sublimetext.com/dev#changelog:~:text=TM_COMMENT_CASE_INSENSITIVE
> Add support for `TM_COMMENT_CASE_INSENSITIVE`

- plugins/command_completions/__init__.py
- plugins/create_package.py
- plugins/lib/fileconv/dumpers.py
- plugins/lib/fileconv/loaders.py
- plugins/new_resource_file/__init__.py
- plugins/syntax_dev/completions.py
This is an alternative to #402 with the problematic commits dropped and some linter fixes applied.
> Address some pylint notices

- Package/TextMate Syntax Definition (YAML)/TextMate Syntax Definition (YAML).YAML-tmLanguage
- Package/TextMate Syntax Definition (YAML)/TextMate Syntax Definition (YAML).tmLanguage
Fixes the rule for matching `match`, `begin`, and `end` multi-line blocks.
> [YAML-tmLanguage] Remove empty capture group from multi-line match rule

- Package/PackageDev.sublime-settings
- Package/Sublime Text Syntax Definition/Sublime Text Syntax Definition.sublime-syntax
- Package/Sublime Text Syntax Definition/syntax_test_sublime-syntax.yaml
- plugins/syntax_dev/completions.py
This PR...
1. adds dedicated contexts/patterns to highlight `extends:` values
2. adds auto-completions for existing syntax definitions when typing within `extends:` values.
> Add support for syntax highlighting and completions of `extends` values

- plugins/syntaxtest_dev.py
Relates to #342, specifically fixing the region highlighting:
> One thing I am excited for is for the highlighting from `^` lines to stop getting stuck on `@` lines. I've added some reference tests, and now clicking on a scope test below a reference test highlights the reference test line instead of the actual line of code to be tested.
> Highlight symbol tests in code lines

- Package/Sublime Text Settings/Sublime Text Settings.sublime-syntax
- Package/Sublime Text Settings/syntax_test_settings.json
Resolves #406
This commit expects a setting namespace to be followed by a valid setting name, but not only numbers.
> Settings: Fix namespace highlighting
